version: "3.7"

# define all containers we want to use
services:
    db:
        image: mcr.microsoft.com/mssql/server
        # define the credentials to be used in our web application
        environment: 
            ACCEPT_EULA: Y
            SA_PASSWORD: 'ashutosh'
        ports:
            - '1434:1433'
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: docker-webapi
        depends_on: 
            - db
        ports:
            - '3000:3000'